[tool.poetry]
name = "alchemy"
version = "0.1.0"
description = ""
authors = ["kawaragi <dima.kretinin.05@mail.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
asyncio = "^3.4.3"
fastapi = "^0.115.4"
requests = "^2.32.3"
alembic = "^1.14.0"
sqlalchemy = "^2.0.36"
psycopg2 = "^2.9.10"
uvicorn = "^0.32.0"
pydantic-settings = "^2.6.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
