"""3

Revision ID: 3b1ca334d373
Revises: 0a1444f2fb65
Create Date: 2024-11-12 18:50:51.080388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b1ca334d373'
down_revision: Union[str, None] = '0a1444f2fb65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('role_id', sa.Integer(), autoincrement=True, nullable=False))
    op.drop_column('roles', 'id')
    op.add_column('users', sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False))
    op.drop_constraint('users_role_id_fkey', 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'roles', ['role_id'], ['role_id'])
    op.drop_column('users', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key('users_role_id_fkey', 'users', 'roles', ['role_id'], ['id'])
    op.drop_column('users', 'user_id')
    op.add_column('roles', sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('roles_id_seq'::regclass)"), autoincrement=True, nullable=False))
    op.drop_column('roles', 'role_id')
    # ### end Alembic commands ###
